// <auto-generated />
using BlazorECommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorECommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorECommerce.Shared.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d4/Never_go_back_by_lee_child.png",
                            description = "Never Go Back is the eighteenth book in the Jack Reacher series written by Lee Child.[1] It was published on 3 September 2013 in the United States",
                            price = 9.99m,
                            title = "Never Go Back"
                        },
                        new
                        {
                            id = 2,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/3c/Killing_floor_by_lee_child_1st_edition_uk.png",
                            description = "Killing Floor is the debut novel by Lee Child, first published in 1997 by Putnam. The book won the Anthony Award and Barry Award for best first novel. It is also the first book to feature the character Jack Reacher. It is written in the first person",
                            price = 9.99m,
                            title = "Killing Floor"
                        },
                        new
                        {
                            id = 3,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/29/Tripwire_book.jpg",
                            description = "Tripwire is the third book in the Jack Reacher series written by Lee Child. It was published in 1999 by Putnam in America and Bantam in the United Kingdom. It is written in the third person. In the novel, retired military police officer Jack Reacher becomes embroiled in a mystery involving a Vietnam War veteran who was reported missing in action, but who has resurfaced as a vicious loanshark with a secret he will murder to protec",
                            price = 9.99m,
                            title = "Trip Wire"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
